<template>
  <ion-page class="terms-page">
    <ion-header class="ion-no-border">
      <ion-toolbar class="vintage-toolbar">
        <ion-buttons slot="start">
          <ion-button @click="goBack">
            <ion-icon :icon="arrowBackOutline"></ion-icon>
          </ion-button>
        </ion-buttons>
        <ion-title>Legal Documents</ion-title>
      </ion-toolbar>
    </ion-header>

    <ion-content :fullscreen="true" class="terms-content">
      <div class="paper-overlay"></div>
      
      <div class="terms-container">
        <!-- Masthead -->
        <div class="masthead">
          <div class="masthead-top">
            <span class="masthead-edition">LEGAL NOTICE</span>
            <span class="masthead-price">EST. 2026</span>
          </div>
          <h1 class="terms-title">Terms of Service</h1>
          <div class="masthead-bottom">
            <div class="motto">User Agreement & Service Terms</div>
            <div class="date">LAST UPDATED: {{ formattedDate }}</div>
          </div>
        </div>

        <!-- Terms Content -->
        <div class="parchment">
          <article class="terms-article">
            <section class="terms-section">
              <h2 class="section-title">1. ACCEPTANCE OF TERMS</h2>
              <div class="article-separator-mini"></div>
              <p class="terms-text">
                By accessing and using The Fold application ("the App"), you acknowledge that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree to these terms, please discontinue use of the App immediately.
              </p>
              <p class="terms-text">
                The Fold is a news aggregation and entertainment application that provides curated content from multiple sources, weather information, and interactive puzzle games for your enjoyment and information.
              </p>
            </section>

            <section class="terms-section">
              <h2 class="section-title">2. THIRD-PARTY SERVICES</h2>
              <div class="article-separator-mini"></div>
              <p class="terms-text">
                The Fold integrates and relies upon the following third-party services to provide its functionality:
              </p>
              <div class="service-list">
                <div class="service-item">
                  <h4 class="service-name">Shadify API</h4>
                  <p class="service-desc">Provides puzzle generation for Anagram, Minesweeper, Word Search, Capitals Quiz, Flags Quiz, Set, Camp (Tents & Trees), and Memory games. All puzzles are dynamically generated via their public API service at shadify.yurace.pro.</p>
                </div>
                <div class="service-item">
                  <h4 class="service-name">Open-Meteo</h4>
                  <p class="service-desc">Supplies real-time meteorological data and weather forecasts displayed in the Weather section.</p>
                </div>
                <div class="service-item">
                  <h4 class="service-name">IPAPI & OpenStreetMap Nominatim</h4>
                  <p class="service-desc">Provides location detection and geocoding services for weather localization.</p>
                </div>
                <div class="service-item">
                  <h4 class="service-name">RSS News Feeds</h4>
                  <p class="service-desc">Content aggregated from 40+ trusted news publishers including Manila Times, Philstar, GMA News, ABS-CBN, Rappler, Inquirer, BBC, Reuters, CNN, and many others.</p>
                </div>
              </div>
              <p class="terms-text">
                We do not control these third-party services and are not responsible for their availability, accuracy, or content. Your use of these services through our App may be subject to their respective terms and policies.
              </p>
            </section>

            <section class="terms-section">
              <h2 class="section-title">3. CONTENT OWNERSHIP & ATTRIBUTION</h2>
              <div class="article-separator-mini"></div>
              <p class="terms-text">
                All news articles, stories, and media content displayed in The Fold belong to their respective original publishers and creators. The Fold does not claim ownership of any third-party content.
              </p>
              <p class="terms-text">
                We make every effort to properly attribute content to its original source. Each news article displays the publisher name and, when available, the author's name. Full credits for all news sources are available in the App Settings.
              </p>
              <p class="terms-text">
                Puzzles and games are generated by the Shadify API and are not created or owned by The Fold. Weather data is provided by Open-Meteo under the Creative Commons Attribution 4.0 International License.
              </p>
            </section>

            <section class="terms-section">
              <h2 class="section-title">4. USER RESPONSIBILITIES</h2>
              <div class="article-separator-mini"></div>
              <p class="terms-text">
                As a user of The Fold, you agree to:
              </p>
              <ul class="terms-list">
                <li>Use the App for lawful purposes only</li>
                <li>Not attempt to reverse-engineer, decompile, or extract source code from the App</li>
                <li>Not abuse, overload, or attempt to gain unauthorized access to our services or third-party APIs</li>
                <li>Respect the intellectual property rights of content creators and publishers</li>
                <li>Not use automated systems or bots to access the App</li>
              </ul>
            </section>

            <section class="terms-section">
              <h2 class="section-title">5. DISCLAIMER OF WARRANTIES</h2>
              <div class="article-separator-mini"></div>
              <p class="terms-text">
                THE FOLD IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO:
              </p>
              <ul class="terms-list">
                <li>Accuracy, reliability, or completeness of news content, weather data, or game functionality</li>
                <li>Uninterrupted or error-free operation of the App</li>
                <li>Availability of third-party services and APIs</li>
                <li>Fitness for a particular purpose or non-infringement</li>
              </ul>
              <p class="terms-text">
                We do not guarantee that the App will meet your requirements or that any errors will be corrected. Use of the App is at your own risk.
              </p>
            </section>

            <section class="terms-section">
              <h2 class="section-title">6. LIMITATION OF LIABILITY</h2>
              <div class="article-separator-mini"></div>
              <p class="terms-text">
                To the fullest extent permitted by law, The Fold and its developers shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from:
              </p>
              <ul class="terms-list">
                <li>Your use or inability to use the App</li>
                <li>Any unauthorized access to or use of our servers</li>
                <li>Any interruption or cessation of transmission to or from the App</li>
                <li>Any bugs, viruses, or other harmful code that may be transmitted through the App</li>
                <li>Any errors or omissions in content or any loss or damage incurred as a result of the use of any content posted or shared through the App</li>
                <li>The unavailability or failure of third-party services</li>
              </ul>
            </section>

            <section class="terms-section">
              <h2 class="section-title">7. PRIVACY & DATA COLLECTION</h2>
              <div class="article-separator-mini"></div>
              <p class="terms-text">
                Your privacy is important to us. The Fold collects minimal data necessary for app functionality. For detailed information about how we collect, use, and protect your data, please review our Privacy Policy available in the App Settings.
              </p>
              <p class="terms-text">
                By using The Fold, you consent to the data practices described in our Privacy Policy.
              </p>
            </section>

            <section class="terms-section">
              <h2 class="section-title">8. MODIFICATIONS TO TERMS</h2>
              <div class="article-separator-mini"></div>
              <p class="terms-text">
                We reserve the right to modify these Terms of Service at any time. Changes will be effective immediately upon posting within the App. Your continued use of The Fold after any such changes constitutes your acceptance of the new Terms of Service.
              </p>
              <p class="terms-text">
                We encourage you to review these terms periodically to stay informed of any updates.
              </p>
            </section>

            <section class="terms-section">
              <h2 class="section-title">9. TERMINATION</h2>
              <div class="article-separator-mini"></div>
              <p class="terms-text">
                We reserve the right to terminate or suspend your access to The Fold immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach these Terms of Service.
              </p>
            </section>

            <section class="terms-section">
              <h2 class="section-title">10. GOVERNING LAW</h2>
              <div class="article-separator-mini"></div>
              <p class="terms-text">
                These Terms shall be governed and construed in accordance with the laws of the Republic of the Philippines, without regard to its conflict of law provisions.
              </p>
            </section>

            <section class="terms-section">
              <h2 class="section-title">11. CONTACT INFORMATION</h2>
              <div class="article-separator-mini"></div>
              <p class="terms-text">
                If you have any questions about these Terms of Service, please contact us:
              </p>
              <div class="contact-box">
                <p class="contact-line"><strong>Email:</strong> cypherstudioindie@gmail.com</p>
                <p class="contact-line"><strong>Website:</strong> mazi39662.github.io/franz_portfolio.com</p>
              </div>
            </section>

            <div class="article-separator"></div>
            
            <footer class="terms-footer">
              <p class="footer-text">By using The Fold, you acknowledge that you have read and understood these Terms of Service and agree to be bound by them.</p>
              <p class="footer-date">Effective Date: January 12, 2026</p>
              <p class="footer-brand">THE FOLD • A NEWS & ENTERTAINMENT APPLICATION</p>
            </footer>
          </article>
        </div>
      </div>
    </ion-content>
  </ion-page>
</template>

<script setup lang="ts">
import {
  IonPage,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonContent,
  IonButtons,
  IonButton,
  IonIcon
} from '@ionic/vue';
import { arrowBackOutline } from 'ionicons/icons';
import { computed } from 'vue';
import { useRouter } from 'vue-router';

const router = useRouter();

const formattedDate = computed(() => {
  return new Intl.DateTimeFormat('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric'
  }).format(new Date()).toUpperCase();
});

const goBack = () => {
  router.back();
};
</script>

<style scoped>
@import url('https://fonts.googleapis.com/css2?family=Old+Standard+TT:ital,wght@0,400;0,700;1,400&family=Playfair+Display:wght@700;900&family=UnifrakturMaguntia&display=swap');

.terms-page {
  --background: #f4ecd8;
}

.vintage-toolbar {
  --background: #f4ecd8;
  --color: #1a1a1a;
  --border-bottom: 2px solid #1a1a1a;
  font-family: 'Old Standard TT', serif;
  font-weight: bold;
}

.terms-content {
  --background: transparent;
  background-color: #f4ecd8;
  position: relative;
}

.paper-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-image: url('/paper-texture.png');
  background-repeat: repeat;
  opacity: 0.15;
  pointer-events: none;
  z-index: -1;
}

.terms-container {
  max-width: 900px;
  margin: 0 auto;
  position: relative;
  z-index: 1;
}

.masthead {
  padding: 20px 20px 10px;
  border-bottom: 5px double #1a1a1a;
  margin-bottom: 25px;
  text-align: center;
}

.masthead-top {
  display: flex;
  justify-content: space-between;
  font-family: 'Old Standard TT', serif;
  font-size: 0.75rem;
  font-weight: 700;
  border-bottom: 1px solid #1a1a1a;
  padding-bottom: 5px;
  margin-bottom: 10px;
  color: #1a1a1a;
  text-transform: uppercase;
}

.terms-title {
  font-family: 'UnifrakturMaguntia', cursive;
  font-size: 3.5rem;
  margin: 10px 0;
  color: #1a1a1a;
  line-height: 1;
  letter-spacing: -1px;
}

.masthead-bottom {
  display: flex;
  justify-content: space-between;
  font-family: 'Old Standard TT', serif;
  font-size: 0.7rem;
  font-weight: 700;
  border-top: 1px solid #1a1a1a;
  padding-top: 5px;
  margin-top: 5px;
  color: #1a1a1a;
}

.parchment {
  padding: 0 15px 60px;
}

.terms-article {
  background: rgba(255, 255, 255, 0.5);
  padding: 30px 20px;
  border: 2px solid #1a1a1a;
  box-shadow: 5px 5px 0 rgba(0, 0, 0, 0.1);
}

.terms-section {
  margin-bottom: 35px;
}

.section-title {
  font-family: 'Old Standard TT', serif;
  font-size: 1.3rem;
  font-weight: 900;
  text-transform: uppercase;
  color: #1a1a1a;
  margin-bottom: 10px;
  letter-spacing: 1px;
}

.article-separator-mini {
  height: 3px;
  border-top: 1px solid #1a1a1a;
  border-bottom: 1px solid #1a1a1a;
  margin-bottom: 15px;
}

.article-separator {
  height: 4px;
  border-top: 1px solid #1a1a1a;
  border-bottom: 1px solid #1a1a1a;
  margin: 30px 0;
}

.terms-text {
  font-family: 'Old Standard TT', serif;
  font-size: 1.05rem;
  line-height: 1.7;
  color: #1a1a1a;
  margin-bottom: 15px;
  text-align: justify;
}

.terms-list {
  font-family: 'Old Standard TT', serif;
  font-size: 1.05rem;
  line-height: 1.7;
  color: #1a1a1a;
  margin: 15px 0 15px 25px;
  padding-left: 10px;
}

.terms-list li {
  margin-bottom: 8px;
}

.service-list {
  margin: 20px 0;
}

.service-item {
  background: rgba(0, 0, 0, 0.03);
  padding: 15px;
  margin-bottom: 12px;
  border-left: 4px solid #1a1a1a;
}

.service-name {
  font-family: 'Old Standard TT', serif;
  font-size: 1.1rem;
  font-weight: 900;
  color: #1a1a1a;
  margin-bottom: 5px;
  text-transform: uppercase;
}

.service-desc {
  font-family: 'Old Standard TT', serif;
  font-size: 1rem;
  line-height: 1.6;
  color: #1a1a1a;
  margin: 0;
}

.contact-box {
  background: rgba(0, 0, 0, 0.05);
  padding: 20px;
  border: 2px solid #1a1a1a;
  margin: 15px 0;
}

.contact-line {
  font-family: 'Old Standard TT', serif;
  font-size: 1.05rem;
  color: #1a1a1a;
  margin: 8px 0;
}

.terms-footer {
  text-align: center;
  padding: 20px 0;
}

.footer-text {
  font-family: 'Old Standard TT', serif;
  font-size: 1rem;
  font-style: italic;
  color: #1a1a1a;
  margin-bottom: 15px;
}

.footer-date {
  font-family: 'Old Standard TT', serif;
  font-size: 0.9rem;
  font-weight: 700;
  color: #1a1a1a;
  margin-bottom: 10px;
  text-transform: uppercase;
}

.footer-brand {
  font-family: 'Old Standard TT', serif;
  font-size: 0.75rem;
  font-weight: 900;
  color: #1a1a1a;
  opacity: 0.6;
  letter-spacing: 2px;
  text-transform: uppercase;
}
</style>
